package com.example.greendaodemo.db;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.example.asus.syoucloud.bean.Lyric;
import com.example.asus.syoucloud.bean.LyricItem;
import com.example.asus.syoucloud.bean.MixItem;
import com.example.asus.syoucloud.bean.MusicAndMixJoin;
import com.example.asus.syoucloud.bean.MusicInfo;

import com.example.greendaodemo.db.LyricDao;
import com.example.greendaodemo.db.LyricItemDao;
import com.example.greendaodemo.db.MixItemDao;
import com.example.greendaodemo.db.MusicAndMixJoinDao;
import com.example.greendaodemo.db.MusicInfoDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig lyricDaoConfig;
    private final DaoConfig lyricItemDaoConfig;
    private final DaoConfig mixItemDaoConfig;
    private final DaoConfig musicAndMixJoinDaoConfig;
    private final DaoConfig musicInfoDaoConfig;

    private final LyricDao lyricDao;
    private final LyricItemDao lyricItemDao;
    private final MixItemDao mixItemDao;
    private final MusicAndMixJoinDao musicAndMixJoinDao;
    private final MusicInfoDao musicInfoDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        lyricDaoConfig = daoConfigMap.get(LyricDao.class).clone();
        lyricDaoConfig.initIdentityScope(type);

        lyricItemDaoConfig = daoConfigMap.get(LyricItemDao.class).clone();
        lyricItemDaoConfig.initIdentityScope(type);

        mixItemDaoConfig = daoConfigMap.get(MixItemDao.class).clone();
        mixItemDaoConfig.initIdentityScope(type);

        musicAndMixJoinDaoConfig = daoConfigMap.get(MusicAndMixJoinDao.class).clone();
        musicAndMixJoinDaoConfig.initIdentityScope(type);

        musicInfoDaoConfig = daoConfigMap.get(MusicInfoDao.class).clone();
        musicInfoDaoConfig.initIdentityScope(type);

        lyricDao = new LyricDao(lyricDaoConfig, this);
        lyricItemDao = new LyricItemDao(lyricItemDaoConfig, this);
        mixItemDao = new MixItemDao(mixItemDaoConfig, this);
        musicAndMixJoinDao = new MusicAndMixJoinDao(musicAndMixJoinDaoConfig, this);
        musicInfoDao = new MusicInfoDao(musicInfoDaoConfig, this);

        registerDao(Lyric.class, lyricDao);
        registerDao(LyricItem.class, lyricItemDao);
        registerDao(MixItem.class, mixItemDao);
        registerDao(MusicAndMixJoin.class, musicAndMixJoinDao);
        registerDao(MusicInfo.class, musicInfoDao);
    }
    
    public void clear() {
        lyricDaoConfig.clearIdentityScope();
        lyricItemDaoConfig.clearIdentityScope();
        mixItemDaoConfig.clearIdentityScope();
        musicAndMixJoinDaoConfig.clearIdentityScope();
        musicInfoDaoConfig.clearIdentityScope();
    }

    public LyricDao getLyricDao() {
        return lyricDao;
    }

    public LyricItemDao getLyricItemDao() {
        return lyricItemDao;
    }

    public MixItemDao getMixItemDao() {
        return mixItemDao;
    }

    public MusicAndMixJoinDao getMusicAndMixJoinDao() {
        return musicAndMixJoinDao;
    }

    public MusicInfoDao getMusicInfoDao() {
        return musicInfoDao;
    }

}
