package com.example.greendaodemo.db;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.example.asus.syoucloud.bean.Lyric;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "LYRIC".
*/
public class LyricDao extends AbstractDao<Lyric, Long> {

    public static final String TABLENAME = "LYRIC";

    /**
     * Properties of entity Lyric.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property LyricId = new Property(0, long.class, "lyricId", true, "_id");
    }

    private DaoSession daoSession;


    public LyricDao(DaoConfig config) {
        super(config);
    }
    
    public LyricDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
        this.daoSession = daoSession;
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"LYRIC\" (" + //
                "\"_id\" INTEGER PRIMARY KEY NOT NULL );"); // 0: lyricId
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"LYRIC\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, Lyric entity) {
        stmt.clearBindings();
        stmt.bindLong(1, entity.getLyricId());
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, Lyric entity) {
        stmt.clearBindings();
        stmt.bindLong(1, entity.getLyricId());
    }

    @Override
    protected final void attachEntity(Lyric entity) {
        super.attachEntity(entity);
        entity.__setDaoSession(daoSession);
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.getLong(offset + 0);
    }    

    @Override
    public Lyric readEntity(Cursor cursor, int offset) {
        Lyric entity = new Lyric( //
            cursor.getLong(offset + 0) // lyricId
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, Lyric entity, int offset) {
        entity.setLyricId(cursor.getLong(offset + 0));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(Lyric entity, long rowId) {
        entity.setLyricId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(Lyric entity) {
        if(entity != null) {
            return entity.getLyricId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(Lyric entity) {
        throw new UnsupportedOperationException("Unsupported for entities with a non-null key");
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
